### ISSUE TITLE
Delimiters of csv files don't match ReadMe

### ISSUE THREAD

**Issue by cpiber** [tugraz-isds/datasets#11]
In the ReadMe it says that the CSV files are delimited by `|` but they actually use `,` as is common

**Comment by mboehm7** [comment]
yes that's true - the readme generally needs an update, which we'll do together with the next batch of cleaning efforts.

**Comment by mboehm7** [comment]
thanks @cpiber - this has been fixed with commit 60c795821add5697da785e81b429c00e2930a6f9
