### ISSUE TITLE
Delimiter at "location" column - matches.csv

### ISSUE THREAD

**Issue by dardand** [tugraz-isds/datasets#2]
I think that the location(name of the stadium and place) at matches.csv should not be separated with comma, since that is the delimiter for the csv file. I would suggest separating the name of the stadium and the place with a dash or a '\'.

**Comment by mboehm7** [comment]
Thanks @dardand for catching this issue. Yes, we should use semicolons or even better re-generate the cleaned data with tab separators. I'll upload it as soon as I get a chance.
