### ISSUE TITLE
SS21 Summer Olympics: Inconsistencies

### ISSUE THREAD

**Issue by codeRed-d** [tugraz-isds/datasets#20]
- AthleteEvent.csv contains 841 athletes that participated in 1906 Intercalated Games, however no such game is present in HostCities.
- AIDs ['31292', '65813'] have no Team and no NOC
- Currently 28993 Athletes have no height, which might be important for a query task

**Comment by codeRed-d** [comment]
AthleteEvents.csv contains possible duplicates in with AIDs:  ['119448', '119449', '125022', '75648', '67492', '67210', '65581', '26037', '8683']

**Comment by mboehm7** [comment]
thanks for pointing out these issues @codeRed-d. For the '1906 Intercalated Games', let's drop the related entries as these grames were intermediate, so no official summer games. Also, having no height is fine and simply used as unknown. 

For the other issues (with missing NOC, duplicates, and multiple medals) we have to follow up. Tomorrow I'll finalize the task description, run the reference solution, and might fix these issues on the fly.

**Comment by mboehm7** [comment]
Thanks for the notes - all raised issues have now been fixed (in fact there were more than a 100 'duplicates' as some events in the early years had multiple competitions). We now simplified the dataset by keeping at most one with the highest medal.
