### ISSUE TITLE
Data contains Null on Squads.csv on Club_Name

### ISSUE THREAD

**Issue by 3Descape** [tugraz-isds/datasets#4]
Hello!
The subsets/1954_2010_Squads.csv contains Null fields in the Club_Name and Club_Country columns. E.g. line 2027

This is agains "Each teamconsists of up to 23 players,[...] number, and a **current club affiliation**."

Is it possible to regenerate the data, so that this gets solved or are we allowed to filter out the data?

Thx

**Comment by mboehm7** [comment]
thanks for pointing this out - this has just been fixed with commit https://github.com/tugraz-isds/datasets/commit/46de3d52156400f3a3d5f4fed86147469fb81a65

**Comment by 3Descape** [comment]
thx
