### ISSUE TITLE
Inconsistencies between Germany and West Germany

### ISSUE THREAD

**Issue by 3Descape** [tugraz-isds/datasets#6]
Hallo!

In subsets/1954_2010_Squads.csv ist z.b. im Jahr 1982 "West Germany" in der Spalte Country angegeben und "Germany" in Club_Country. Das wäre ja an sich noch nicht schlimm.

Problematisch wird es wenn man sich noch die Tabelle subsets/1954_2010_Matches.csv anschaut.
Hier wird wieder z.b. im Jahr 1982 "West Germany" bei Team1/Team2 verwendet, womit keine zuverlässige zuordnung gemacht werden kann.

Beispiel: Der Spieler Reinhold Hintermaier(Zeile 2496 in subsets/Squads) Spielt beim Club Nuremberg aus "Germany". In subsets/Matches.csv Zeile 243 Team 1 gibt es auf einmal ein Team "West Germany", obwohl es dieses Team laut Squads.csv ja gar nicht gibt, da die Spieler für "Germany" spielen.

Daher der Vorlschag:
Entweder alles einheitlich in "Germany" umbenennen oder in den Jahren, in denen "West Germany" vorkommt, immer nur "West Germany" verwenden.

**Comment by mboehm7** [comment]
thanks again - I fixed this to historical correct names for clubs, similar to how we handled Yugoslavia and Croatia so far.
