### ISSUE TITLE
Soviet Union hat 1990 kein Team, spielt aber mit

### ISSUE THREAD

**Issue by 3Descape** [tugraz-isds/datasets#8]
Hallo
Sie "Soviet Union" spielt in subsets/Matches.csv im jahr 1990 mehrere Male mit, hat aber in subsets/Squads.csv kein Team im Jahr 1990

**Comment by 3Descape** [comment]
Gleiches Problem bei  "Côte d'Ivoire" im Jahr 2006

**Comment by 3Descape** [comment]
Gleiches Problem bei "Nigeria" im Jahr 2010

**Comment by mboehm7** [comment]
Maybe I'm misunderstanding the question but the mentioned teams do exist in `1954_2014_Squads.csv`:

```
1990 Soviet Union (starting line 3957)
2006 Côte d'Ivoire (starting line 6128)
2010 Nigeria (starting 7232)
```

**Comment by 3Descape** [comment]
ok, thx.. I misinterpreted the data.. I've used the wrong column..
The data seems to migrate fine now, will have to check though..

Thank you very much!
